# Use postgres/example user/password credentials
# version: '3.1'

services:
  db:
    image: postgres:14.9
    restart: always
    ports:
      - "9877:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: k1_admin