"""New property for User

Revision ID: 454deb3a198c
Revises: d277b9811193
Create Date: 2025-04-20 13:38:13.349155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '454deb3a198c'
down_revision: Union[str, None] = 'd277b9811193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['tg_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'tg_id')
    # ### end Alembic commands ###
